### ISSUE TITLE
Why does reverseproxy use instance hostname as opposed to IP address?

### ISSUE THREAD

**Issue by kyrofa** [alchemy-charmers/charm-gitlab#14]
I'm not actually sure if this is a gitlab bug or an haproxy bug, so please point me in the proper direction if I'm on the wrong path.

So I configure gitlab with a hostname (e.g. `external_url=http://example.com`), and then I connect it to haproxy's reverseproxy relation. While haproxy uses example.com in the frontend to make sure it uses the proper backend, it uses gitlab's own hostname in the backend. This works with a lxd cloud, but in openstack there's not always a DNS server to resolve those. The redis and postgresql charms use IP addresses instead of hostnames, is there a reason gitlab doesn't do the same? Manually replacing the hostname in haproxy's config with gitlab's IP address works, but obviously isn't the most maintainable.

**Comment by chris-sanders** [comment]
If your environment isn't using static IP addresses defaulting to an IP address would cause a random failure when it changed. In general we default our charms to using fqdn because DNS should be reliable regardless of your IP/network setup. If your environment doesn't have working DNS I'd personally solve that first. 

However some of the charms have an option to let you choose if the reverseproxy will register with IP or hostname and that could be implemented here as well. Do you have multiple networks? I presume we need to get the IP used by reverseproxy endpoint and that would solve the issue?

Is there any particular reason you don't want to or can't use DNS?

**Comment by kyrofa** [comment]
> Is there any particular reason you don't want to or can't use DNS?

I'm running in an openstack environment that doesn't have instance DNS, and I don't seem to have any control over that. Note that the environment DOES have DNS, it just doesn't resolve other instances.

> However some of the charms have an option to let you choose if the reverseproxy will register with IP or hostname and that could be implemented here as well.

Yeah that would work.

> Do you have multiple networks? I presume we need to get the IP used by reverseproxy endpoint and that would solve the issue?

I don't have multiple networks in this case, I think that would work fine.
